# Generated by Django 6.0.2 on 2026-02-08 20:28

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    for name in ["MEMBER", "LIBRARIAN"]:
        Group.objects.get_or_create(name=name)

def reverse_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["MEMBER", "LIBRARIAN"]).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_groups),
    ]
